### ISSUE TITLE
Park Tiles Overlay defaulting to off when Places Editor is first loaded

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-editor#100]
Probably related to the hash, but this is a big problem. It's really confusing to jump into the Editor and have no park boundaries to orient yourself.

**Comment by jimmyrocks** [comment]
This one is pretty strange, it seems like it's only a problem when being loaded from the inside-maps link. I can't see to replicate it in the dev version. The Park Tiles Overlay is set as default, so it should always be on, and doesn't need to be in the hash for it to be loaded.

I'll be moving my testing from dev to a new directory on insidemaps to see if I can replicate it elsewhere.

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-editor/commit/b28f85c9af633ff7f7e218c0800cf5cbc6e581ad
