### ISSUE TITLE
Connect basemap to new places_boundaries `parks` table

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#104]

**Comment by cwlawlis802** [comment]
cc @mtaylorlong @jakecoolidge @jimmyrocks

**Comment by jakecoolidge** [comment]
Styles went up to Mapbox this morning, pulling boundaries and labeling from nps.nps-places-reference.

**Comment by jakecoolidge** [comment]
mapbox-studio-projects repo also updated
