### ISSUE TITLE
Update boundary source

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#110]
The tiles in view-only mode appear to be correct, but they are incorrect/outdated once in edit mode.

cc @mtaylorlong @jakecoolidge @jimmyrocks

**Comment by cwlawlis802** [comment]
The boundaries in both view and edit modes appear to be outdated.

@mtaylorlong and @jakecoolidge are investigating and potentially creating a new, cleaned up source for both.

Repo tracking sources/styles feeding into Editor: https://github.com/nationalparkservice/mapbox-studio-projects/tree/master/places_editor_viewer.

Current boundary/label style: https://api.mapbox.com/v4/nps.5c677638/page.html?access_token=pk.eyJ1IjoibnBzIiwiYSI6IkdfeS1OY1UifQ.K8Qn5ojTw4RV1GwBlsci-Q#10/37.8450/-122.2971.

See also https://github.com/nationalparkservice/places-data/issues/634.

**Comment by jakecoolidge** [comment]
The map visible in view-only mode is now pulling from nps.nps-places-boundaries-v2 with current label settings.
