### ISSUE TITLE
Places contains many POIs outside of a park boundary

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#16]
POI DB contains many POI's outside of a park boundary, such as cemeteries around GRSM. Is this the default/correct behavior? Should they be deleted or edited?

**Comment by nateirwin** [comment]
We decided that we'll support data outside of a park boundary, but we won't use it in Park Tiles. So we should encourage people to stick to creating/maintaining data within their boundary, but aren't going to stop them from creating data outside.
