### ISSUE TITLE
List of POIs doesn't populate with all options

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-editor#25]
I'm not sure if this is by design, but when a point is added, the list on the left doesn't populate with all available options for POIs.  Users obviously can search for a POI type but do they know what is searchable/addable?

**Comment by jimmyrocks** [comment]
@nateirwin and I created a list of nodes and ways that we would like to use, not everything will show up, but everything we support is searchable
https://github.com/nationalparkservice/places-editor/commit/c4fa3cfe1c9d9b5bb534d3b8d658d12170594ab7
