### ISSUE TITLE
Add inset map feature

### ISSUE THREAD

**Issue by MappingKat** [nationalparkservice/places-editor#30]
As a use that does not know the parks very well, it would be useful just to have a pop up or inset map that shows where I am on the park.  Just would make editing and moving around the map more easy.

**Comment by ethomas33** [comment]
I would also like it to be clickable to make changing from one place in the park to another easier and faster. Or to be able to have a list of things that are preset zoom views that can be switched between.

**Comment by nateirwin** [comment]
This is actually available in Places Editor now (via https://github.com/openstreetmap/iD/issues/2602), but we need to make it more obvious. In Editor, press the `/` key and an inset map should display. I'm going to leave this open for now.

**Comment by ethomas33** [comment]
Possibly documentation as a simple "help" button to present all the keyboard shortcuts for the system which would help not just this but streamline other things too.

**Comment by bhousel** [comment]
> Possibly documentation as a simple "help" button to present all the keyboard shortcuts for the system which would help not just this but streamline other things too.

Yes I'm planning to add a keyboard shortcuts screen soon for openstreetmap/iD#1481 as the '?' key.  It will work pretty much the same way '?' works on GitHub..

**Comment by nateirwin** [comment]
That'll be great, @bhousel.
