### ISSUE TITLE
HTTP Get Lookups

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-editor#34]
We want to be able to do a lookup request with the following parameters

* type=a,b,c,d,e,f,g
  * These are types as defined by the "name" field in the JSON files
* center=lat,lon
  * the center point for the query, this will also require a distance to be set
* distance=meters
  * the distance from the center point in meters
* bbox=minLon,minLat,maxLon,maxLat
  * this uses the standard bbox order
* unit_code=ABCD
  * accepts a park's 4 letter unit/alpha code

**Comment by nateirwin** [comment]
We're using the CartoDB mirror for this now. Closing.
