### ISSUE TITLE
Park (unit/alpha) codes get added when a point, line, or area is added

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-editor#35]
name should be a good enough description

**Comment by tpcolson** [comment]
Recommend turning this off for line nodes? The nps:unit_code is tagged to each node of a trail line, this could be many hundreds of thousands of nps:unit_code=ABCD for a big park.

**Comment by nateirwin** [comment]
I actually think it might be important to have unit_code for nodes that are part of a line or polygon. One example I can think of off the top of my head is entrance/exit points for a building.

**Comment by jimmyrocks** [comment]
So, I thought about this a little bit, and we can make it so nodes only get
a uuid and unit_code IF they are deemed "interesting".  Which means it has
any tags that are not "nps:*" tags.

so a node with tags:
nps:source GRSM
amenity: toilet

would be interesting and would get a uuid and a unit_code

where a node like:
nps:source GRSM
nps:unit_code grsm

would not be interesting, and would not get a uuid, and since it has a
unit_code already, we won't strip that out, but we also won't update it

Thoughts?

**Comment by nateirwin** [comment]
Follow up on this one, @jimmyrocks? Seems like it is no longer an issue?

**Comment by jimmyrocks** [comment]
No longer an issue since we don't add unit_codes to places automatically
anymore. They are still added before being pushed out to cartodb though.
