### ISSUE TITLE
nps:unit_code not honored (Trails)

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#42]
In JOSM, but this likely is issue in ID as well: 

When adding nps:unit_code and a park code that is not the home unit tied to the editors account, on upload data, the unit code is tagged as editors home unit regardless of what editor tagged;

When adding a new trail, on upload/save, nps:unit_code is tagged as editors home unit. Upon subsequent edit/update of a previously saved and posted trail, nps:unit_code  is INTERMITTENTLY overwritten with editors home unit regardless of unit code entered. 

This would be an issue for regional/national editors that are posting or editing another parks trails.

**Comment by nateirwin** [comment]
This is fixed. `unit_code` is no longer added automatically.
