### ISSUE TITLE
Splitting a line at a node results in duplicate UUID's

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#43]
In a situation where trails have been uploaded to the PlacesDB via some method of upload other than Through ID (e.g JOSM, Direct Import) and an editor then edits one of the uploaded trails through ID by splitting a trail (line) at an intersection node, the resulting split allows the editor to save the edit with aduplicate UUID (nps:places_id). 

This would arise in situations where a data steward did not honor spatial geometry rules and trails intersect other trails with no line split occurring at the intersection and those trails were imported into Places. Not sure if that geometry violation will prevent routing from working.

**Comment by tpcolson** [comment]
This also occurs in Places-Public

**Comment by jimmyrocks** [comment]
uuids are removed
