### ISSUE TITLE
Public-facing places editor should generate notification to park

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#47]
When an edit is made to the Public-facing places editor, some sort of notification based on a geo-trigger should go to the park-designated data steward of GIS data, where some sort of approval process occurs before the edit is accepted by the NPS. I understand a tool for this is in the works, and emphasize that permission to use this tool be carefully vetted.

**Comment by jimmyrocks** [comment]
The idea of making this public editor is that we're going to let people use it for just this weekend. It'll be taken down after that. Next week, I will pushing some metrics on what people edited. It's mostly a way to get some new data into our system and look into what we need to do to take public contributions.

**Comment by nateirwin** [comment]
Closing for now.
