### ISSUE TITLE
Public-places editor not honoring some existing tags

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#48]
Some items that are in Places pre-migration to new public DB have tags that ID is not picking up: For example, b1e6e219-aac2-46f0-bd38-e43e5455b214 is tagged horse=no yet Places Public ID editor shows horses=yes in GUI and not horse tag at all in "All Tags" unless I select horse=no. Presumably, if the tag already exists, it should show up in ID with the existing value?

**Comment by jimmyrocks** [comment]
This is kind of a weird thing about iD in general. It is something we should look into, especially if it's confusing to the users. The data in Public Places is about a week old, I'll be updating it before I leave the office tonight.

**Comment by tpcolson** [comment]
It seems intermittent.

**Comment by nateirwin** [comment]
Closing for now. We aren't actively supporting the public-facing Places Editor, so this is something we can look into later.
