### ISSUE TITLE
Park area not shown in editor mode - unsure where to edit

### ISSUE THREAD

**Issue by TheMapSmith** [nationalparkservice/places-editor#49]
This looks great! I was looking to make some edits but I found myself not knowing where to focus. I think the problem is that in Editor mode the park boundary isn't shown. 

When in viewer mode, the park is clearly visible:
![image](https://cloud.githubusercontent.com/assets/8357118/7120069/66b5ec6a-e1d8-11e4-952a-d5cf29a48758.png)

When you click on "Switch to Editor", the extents of the park are no longer obvious from a plain satellite image. Users unfamiliar with the area won't know where to focus their edits 
![image](https://cloud.githubusercontent.com/assets/8357118/7120084/801b41c8-e1d8-11e4-92bb-a39ec93b9359.png)

There are obviously many ways to get around this, but one thought that popped into my head was maybe have the area outside of the park bounds "darkened" with a map overlay so that the park area appears highlighted?

**Comment by jimmyrocks** [comment]
Thanks for the suggestion! We do the "darkened" maps on our state pages, and they seem to work well there. We have some overlays available during edit mode, but none of them have the park boundaries displayed.

**Comment by jimmyrocks** [comment]
We updated the overlay to include parks

**Comment by cwlawlis802** [comment]
Reopening this - unit boundaries render when in View mode, but when zoomed in far enough to edit (Edit mode) the boundaries disappear, leaving the user unsure of where to focus.

**Comment by cwlawlis802** [comment]
cc @jimmyrocks

**Comment by cwlawlis802** [comment]
This seems to be working today so I'm going to close this for now. Will reopen if issue persists.
