### ISSUE TITLE
Display name of current park as you pan/zoom in both view and edit interfaces

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-editor#53]

**Comment by jimmyrocks** [comment]
Not in the view interface

**Comment by nateirwin** [comment]
Good job, @jimmyrocks! I was thinking, however, that we could update the select above and to the right of the map in both the view and edit interfaces (see screenshot below).

![editor___places___insidemaps](https://cloud.githubusercontent.com/assets/10443/7537668/d85c6226-f557-11e4-8e18-92499c707b59.jpg)

Thoughts?

**Comment by jimmyrocks** [comment]
I was thinking about doing that as well, but I was having trouble with the iframe / parent interaction and disabling the onChange function when the field got updated. We can look more into it though.

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-editor/commit/c8b53dc212c6a704ca832cc4a351342ae9de7fb2

https://github.com/nationalparkservice/places-editor/commit/606e913df83cfe648b3a78fa120a96152cad0606
