### ISSUE TITLE
Adding highway=track to piste:type= trails

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#54]
It appears `highway=track` has been left out of the following trail types in the [NPS_Places_Presets document](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272):
* Downhill ski trail `{"piste:type":"downhill"}`
* Cross-country ski trail `{"piste:type":"nordic"}`
* Sledding `{"piste:type":"sled"}`
* Snowshoe trail `{"piste:type":"hike"}`

@asouthwould was this intentional? No worries if not, we just need to add them back in to make sure these trails are tagged appropriately moving forward. We're using Regan's script, which translates directly from the spreadsheet, so we'll be updating this to reflect the most up to date tagging.

**Comment by asouthwould** [comment]
We decided trails would be tagged with highway=path for travel more like "foot traffic" and highway=track for the rest. I tagged all the highway=track appropriately and I'm not sure why I didn't tag these with highway=path. I'll make those changes to the spreadsheet. 

When the data is processed from GIS to OSM, there should be an evaluation to determine the highway value for instances where more than one use is allowed. Ex. If uses are hike and snowshoe, then highway=path. If uses are hike and bike, then highway = track. 

Thanks for catching that!

**Comment by cwlawlis802** [comment]
Thanks Angie. What do you think about changing downhill ski trail, cross-country ski trail, and sledding trail to `highway=track`? I think snowshoe trail makes sense as `highway=path` to stay consistent with the "foot traffic" classification, but not sure if the others fall in line with that. 

In the tracing guide I have classified trails into 3 general groupings:
1. Trail (footpath), intended for "foot traffic"
1. Multi-use trail, including the ATV trail, bicycle trail, equestrian trail, etc
1. Water trail, including waterways intended for motorized and non-motorized watercraft

Let me know what you think. I know we came to a consensus on this during the mapathon, so if this change doesn't make sense to you let me know and I am okay with keeping as is.

**Comment by jimmyrocks** [comment]
OpenStreetMap doesn't use highway=track for downhill skiing (
http://wiki.openstreetmap.org/wiki/Key:piste:type)

It probably wouldn't make a difference to the renderers to add it or not
though.

Ski trails are very far off from what OSM is defining as track "roads for
mostly agricultural use, forest tracks"  (
http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack)

But if we're completely changing the meaning of track, then it might fit.

**Comment by cwlawlis802** [comment]
Hm, good point @jimmyrocks. I remember we wanted to maintain a simplified and consistent structure for trails, using only `highway=path` and `highway=track` but `route=piste` does seem to make sense for ski trails, especially for integration with OSM. I don't think that would overcomplicate things given we're still using the `piste:type=` tag for these trails, so I'm on board with implementing that instead.

@asouthwould what do you think?

**Comment by asouthwould** [comment]
We may need to rethink our highway=track assignment all together.

I don't know how I've missed this before, but OSM defines path as "...is a generic path, either multi-use or unspecified usage, open to all non-motorized vehicles. The path may have any type of surface. This includes walking and hiking trails, bike trails and paths, horse and stock trails, mountain bike trails, ski (Disputed) and snowmobile trails (Disputed) as well as combinations of the above." 

(http://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath)

Should we reclassify our trail types so that if motorized access is allowed then highway=track and if only non-motorized use is allowed then highway=path? The definition for highway=path lists skiing, though disputed. It also lists snowmobiles even though that is clearly motorized and is also disputed. In this case, your 3 general groups could become:

1. Trails that allow non-motorized use only. (highway=path)
2. Trails that allow motorized use and may also include non-motorized use. (highway=track)
3. Water trails.

**Comment by cwlawlis802** [comment]
Makes sense to me. I say we stay consistent with the motorized vs. non-motorized classification for `highway=path` vs. `highway=track` meaning the groupings would be as follows:

`highway=path`
* Footpath
* Bicycle trail
* Equestrian trail

`highway=track`
* ATV trail
* Four-wheel drive trail
* Motorcycle trail
* Snowmobile trail

Water trails would remain as is. I am still torn about how to integrate the tags reliant on `piste:type=`:

* Dog sled trail
* Snowshoe trail
* Downhill ski trail
* Cross-country ski trail

Would these make sense associated with `highway=path`? They are intended as classifications of `route=piste` and are seasonal in practice so it seems logical to maintain this. It does, however, bring yet another trail classification into the mix which I recognize could complicate things (both for the contributor and potentially cartographically).

**Comment by cwlawlis802** [comment]
Okay, trail types have been [fully reclassified in the guide](http://nationalparkservice.github.io/places-tracing-guide/#trails), along with changes to the winter sport tags using `route=piste` and `piste:type=` in the [presets google doc](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272) (add Backcountry Ski Trail and Sledding to the list [above](https://github.com/nationalparkservice/places-editor/issues/54#issuecomment-109099417)).

Should be all set here.
