### ISSUE TITLE
Not all parks are in the dropdown

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-editor#55]
Specifically "Castle Clinton", but this causes issues with the "updating when the map is moved" feature.

This should use the list from the CartoDB parks table.

**Comment by nateirwin** [comment]
To support this, can you write an optimized script for pulling the unit code, park name, and bounding box for all parks from our CartoDB "parks" table? I can then use this in both places-editor and in NPMap.js (to drive the geocoder control).

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-editor/commit/00a63520c3bf5f438e5a27f61b4ba5a92d20c798
