### ISSUE TITLE
unable to select lines or polygons in editor

### ISSUE THREAD

**Issue by ethomas33** [nationalparkservice/places-editor#57]
The last two days I have on and off had a problem of selecting lines or polygons to edit them in any way I can roll over them and they will highlight but nothing will happen when clicking on them, I can also create new ones but once I click off nothing. I have logged out and logged back in with no change. Yesterday it just suddenly started working again not sure if there is anything changing on your end but it just quit working again.

**Comment by nateirwin** [comment]
Status update, @jimmyrocks? Seems like this is an iD issue?

**Comment by jimmyrocks** [comment]
Is this still occurring? I haven't looked into it further than trying it
that day and not being able to reproduce it. I recommend leaving this issue
open and commenting on it if there are any similar issues that come up so
we can look into it in more detail once we have more information.

**Comment by nateirwin** [comment]
I haven't been able to reproduce, so I'm going to close for now. @ethomas33 can you reopen if you continue to see this issue?

**Comment by ethomas33** [comment]
Sorry was on vacation. I will I haven't touched it in two weeks I will let you know what happens!
