### ISSUE TITLE
Global search returns features outside of NPS

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#6]
Searching for things in the editor appears to be searching OSM AND the NPS POI DB. Eg, searching for "Knoxville" returns many items, none related to NPS. This could be confusing to some ID editors that are searching for a commonly-spelled feature in their park.

**Comment by nateirwin** [comment]
I actually think we should leave this one for now. It is nice to be able to search for a location and jump to it. We can revisit in the future once we have more/better NPS data to search.
