### ISSUE TITLE
Make sure all presets have a marker

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-editor#60]
In the screenshot, "Backcountry Ski Trail" has a generic marker (which is good), but there is no marker for "Four-Wheel Drive Trail."

![id](https://cloud.githubusercontent.com/assets/10443/8236195/00f0a140-15a4-11e5-94df-89194882cc98.jpg)

**Comment by jimmyrocks** [comment]
This will need to be fixed at either a) the presets level or b) the maki level.
https://github.com/nationalparkservice/places-data/issues/59

**Comment by jimmyrocks** [comment]
If the maki type is not recognized, it will assign a default icon
