### ISSUE TITLE
Review and update help docs

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-editor#61]
We need to give the help docs one more review to take care of issues like the one in the screenshot below (we no longer use a Bing Maps satellite layer).

![id](https://cloud.githubusercontent.com/assets/10443/8236513/1eaaa77e-15a6-11e5-950e-1275502a7671.jpg)

**Comment by cwlawlis802** [comment]
Content here: [https://github.com/nationalparkservice/places-editor/blob/master/data/core.yaml#L418](https://github.com/nationalparkservice/places-editor/blob/master/data/core.yaml#L418)

**Comment by cwlawlis802** [comment]
Review/update completed locally, need to sort [this](https://github.com/nationalparkservice/places-editor/issues/64) out before pushing changes...

**Comment by cwlawlis802** [comment]
All set here. Accidental merge branch was [sorted out](https://github.com/nationalparkservice/places-editor/issues/64) and [help doc modifications were implemented](https://github.com/nationalparkservice/places-editor/commit/54942203d789f8bcaad4a56b872ebab1b292e0c4).
