### ISSUE TITLE
Accidental merge branch master

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#64]
When trying to push changes to the `core.yaml` to [update the sidebar help doc](https://github.com/nationalparkservice/places-editor/issues/61#event-334394964) I somehow managed to [merge branch master](https://github.com/nationalparkservice/places-editor/commit/1e48a6f90d010f2982e67b31c8bccbbc3f51389b)...

@jimmyrocks @nateirwin can you take a look at this? I imagine we need to revert this commit...

**Comment by jimmyrocks** [comment]
Thanks for point this out! I can revert this and then remerge it

**Comment by cwlawlis802** [comment]
All set here, thanks for the revert @jimmyrocks :smile: 

To note: simple changes to the editor can be pushed directly to `Master` moving forward, just make sure to pull before pushing. Best practice is to create another working branch and merge changes that way, especially for larger modifications.
