### ISSUE TITLE
Add new Places Editor Viewer map

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-editor#66]
Here's a preview in Builder of two mapbox styles (an overlay and a basemap) that draw OSM data outside the parks, and Places data inside the parks. The styling is meant to reference the edit mode, particular the roads and polygons.

http://www.nps.gov/maps/full.html?mapId=1aa2eb20-1276-4299-bfbf-c2a41da247f5

Of course, edits and corrections can be made prior to integration.

**Comment by jakecoolidge** [comment]
Here are the Mapbox ids:
Overlay: nps.8e8c74c9
Base: nps.5d3811a3

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-editor/commit/25bd920ff4253a272b3c6226bdd73955e5aafda6

**Comment by makella** [comment]
@jakecoolidge this is great.  

Can you do some colorblind testing on the map?  I think the orange and red used on two different road classes are not distinguishable enough on the viewer map. 

Example: http://insidemaps.nps.gov/places/view/#15/37.7892/-122.4410 

Also, the transparency applied to the building footprints is getting lost in the green polygon fill when viewed under Deuteranopia conditions. An easy solution for this might be to just remove the transparency.

Here is an example at zoom 15: http://insidemaps.nps.gov/places/view/#15/40.5981/-74.0689

As mentioned a while back, these are some of the tools we use to test:
https://github.com/nationalparkservice/npmap-scratch/tree/master/cartography/symbology

No Coffee is a Chrome extension and can be used in the browser while panning/zooming and navigating web maps or anything else on the web.  Color Oracle is good too but doesn't have the same capabilities for interacting with the page/map.

Also, it looks like roads are getting symbolized with different colors even though they are not in Places.  I'm noticing it mainly with major roads and highways.  Is it possible to reserve the coloring for these road classes inside of park boundaries?

Example: http://insidemaps.nps.gov/places/view/#15/40.6844/-73.9733

mamata

**Comment by jimmyrocks** [comment]
Mamata,

Thanks for pointing out the colorblind limitations.

Jake,

If you find that you need to change some of the colors, let me know and we
can explore changing the colors in the editor as well.

**Comment by jakecoolidge** [comment]
I agree, we would want them to be consistent, and the Viewer styles are informed by the styles in Editor. 

I'll look into this today and keep you guys in the loop.
