### ISSUE TITLE
Crosswalks should have similar form treatment as bridges and tunnels

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-editor#67]
Crosswalks are everywhere, and it is important that we capture them in our data, as we need this information to add accessibility information to Places Mobile apps. Currently you have to manually add a tag to designate a section of a sidewalk or trail as a crosswalk. I think we need to make this more intuitive in Places Editor.

It is easy to designate a section as a bridge or a tunnel:

![editor___places___insidemaps](https://cloud.githubusercontent.com/assets/10443/8314501/1f686656-19a7-11e5-9ee8-25b3798c5993.jpg)

We should also make it similarly easy to designate a crosswalk.

**Comment by cwlawlis802** [comment]
The best practice is a little confusing/complex according to the wikis: 

http://wiki.openstreetmap.org/wiki/Key:crossing

http://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing (see `Examples` section, image below)

![](http://wiki.openstreetmap.org/w/images/c/cb/Footway%3Dcrossing_four-way_intersection.jpg)

Discussed this with @jimmyrocks and he is going to ask the community before we move forward.

**Comment by cwlawlis802** [comment]
Okay, see https://lists.openstreetmap.org/pipermail/newbies/2010-April/005268.html

Best practice appears to be adding a node to the associated way in the middle of the crosswalk tagged `highway=crossing` along with access (foot, bicycle, horse, etc).

**Comment by nateirwin** [comment]
Guess I disagree with this.

One of our primary use cases is using geolocation to let a visually-impaired user know when they are entering a crosswalk and then leaving it again. I feel like we won't be able to get the granularity we need with a point feature. A crosswalk seems like a linear feature to me.

**Comment by cwlawlis802** [comment]
Ya, I agree. Another approach is to tag the crosswalk using a node in the middle and connect to it from the sidewalk using `footway=crosswalk`.

I'll let @jimmyrocks chime in here on the results from his crowdsourcing efforts :smile:

**Comment by jimmyrocks** [comment]
I'm researching just using crossing=yes, seems easy from our point of view,
and like it won't break anything in OSM.

**Comment by nateirwin** [comment]
+1

Seems like it is easy to implement and we can always adjust in the future, if needed.

**Comment by jimmyrocks** [comment]
Looks like we're good to go with this idea

`I would expect any of these should be understood as a crosswalk by data consumers:
  highway=footway,  footway = crossing
  highway=cycleway,  cycleway = crossing
  highway=path,  path = crossing`

How about we get rid of "ford", "cutting", and "embankment" from "structure".. and maybe change it from "structure" to some other name? 

#Ambitious

**Comment by nateirwin** [comment]
I would say let's just add it to the structure section for now. And we can just leave the others.

Low-hanging fruit ;-)

**Comment by cwlawlis802** [comment]
+1

Are we sticking with `crossing=yes` or are we supporting all of these?

> `I would expect any of these should be understood as a crosswalk by data consumers: highway=footway, footway = crossing highway=cycleway, cycleway = crossing highway=path, path = crossing`

**Comment by jimmyrocks** [comment]
Let's just do `crossing=yes`

**Comment by cwlawlis802** [comment]
Updated in the guide: https://github.com/nationalparkservice/places-tracing-guide/commit/f42be8d0f93bb57a26223eddc514e149545b1f07

**Comment by jimmyrocks** [comment]
Added to iD, I even gave it a slightly different style in iD
![screen shot 2015-06-24 at 11 24 31 am](https://cloud.githubusercontent.com/assets/98192/8336714/9d7f9908-1a63-11e5-8922-3e4eeffb0285.png)
