### ISSUE TITLE
Update Campground icon

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#68]
Campground icon is outdated, currently set to same icon as Campsite:

![preset_campground](https://cloud.githubusercontent.com/assets/1238636/8415588/1ae43f1e-1e5d-11e5-8cff-10c9882117f9.jpg)

Should be https://github.com/nationalparkservice/npmap-symbol-library/blob/gh-pages/pngs/campground-black-24.png.

**Comment by jimmyrocks** [comment]
Updated in the spreadsheet, it'll be in the next editor release:
https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272
