### ISSUE TITLE
Implement colorblind-compatible version of Places Editor Viewer

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-editor#69]
Using colors @makella has developed and looking over some of the sequential color schemes on ColorBrewer, I've come up with a new variation for the Places Editor Viewer:

http://www.nps.gov/maps/full.html?mapId=b1ec9b4d-7e9d-4539-9c26-99fe763bf38b

@jimmyrocks we can talk about what this could like in the Edit mode. Below are some images that show the new symbols over a variety of backgrounds, and how they appear under Deuteranopia.
![colorblind-symbols-park-fill](https://cloud.githubusercontent.com/assets/11392872/8458554/f9f56098-1fd4-11e5-8dfb-9577c0b35d68.png)
![deuteranopia_park-fill](https://cloud.githubusercontent.com/assets/11392872/8458556/f9fa14ee-1fd4-11e5-81ac-0b10837facf5.png)
![colorblind-symbols-imagery-dark-forest](https://cloud.githubusercontent.com/assets/11392872/8458552/f9eafd4c-1fd4-11e5-9f40-ad52c58718b1.png)
![deuteranopia_imagery-dark-forest](https://cloud.githubusercontent.com/assets/11392872/8458555/f9f5f850-1fd4-11e5-84c4-1b8bfbdd90b9.png)
![colorblind-symbols-imagery-light-desert](https://cloud.githubusercontent.com/assets/11392872/8458553/f9ed8486-1fd4-11e5-81ab-b95c9fcd3697.png)
![deuteranopia_imagery-light-desert](https://cloud.githubusercontent.com/assets/11392872/8458557/f9fad758-1fd4-11e5-84c3-9c07964b0e78.png)

**Comment by makella** [comment]
nice!

**Comment by jakecoolidge** [comment]
Yeah, I like these colors!

**Comment by ethomas33** [comment]
I think those are spot on! I am surprised how well they show up on the varying backgrounds.

**Comment by jakecoolidge** [comment]
done!

**Comment by makella** [comment]
Hi Jake,

Based on what Nate was talking about last week during scrum, I too think it would be a good idea to have the Places Editor basemap be an imagery one. The main reason being that if you switch to editor view and are not zoomed in far enough, you lose all the detail that was there in the first place on the Park Tiles Editor map and are back to square one of finding where to zoom in.  I was playing around with the editor and found it difficult to navigate to exactly where I wanted to go.

If we keep the entire Places Editor experience an imagery one, it will likely lead to even less confusion.

Let us know what you think.

mamata

**Comment by jakecoolidge** [comment]
I've created a [new issue](https://github.com/nationalparkservice/places-editor/issues/74) to implement this.
