### ISSUE TITLE
Add a disclaimer to Places Editor re: currency of Viewer basemap

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-editor#70]
I had a recent user wondering why his updates weren't reflected in the map in Places Editor (the Viewer basemap, not the edit mode); I let him know that the data will eventually be visible in the Viewer basemap, but it takes a little while to appear. It made me think we might include a disclaimer somewhere in the interface that speaks to this. Something along the lines of, 
"Please note, the data represented here reflects a snapshot of the data current to within (x amount of time)." 
We may not want to be too specific with the time interval. Thoughts?

**Comment by nateirwin** [comment]
I think this is a good interim fix. I'll take this one on.

**Comment by nateirwin** [comment]
How is this?

![editor___places___insidemaps](https://cloud.githubusercontent.com/assets/10443/8463885/56b6339a-1ffb-11e5-82f9-f90306e6fe52.jpg)

**Comment by jakecoolidge** [comment]
Seems like a good approach to me. One business day sets a reasonable expectation, though @jimmyrocks probably has more perspective regarding the time frame.

**Comment by nateirwin** [comment]
Ok, this is out. We can update the text if we need to.
