### ISSUE TITLE
Sledding preset not available

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#72]
Listed in [spreadsheet](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272) as `piste:type=sled`

**Comment by jimmyrocks** [comment]
In the spreadsheet, sledding is only available as a point. It is available in the editor as a point.

**Comment by cwlawlis802** [comment]
Ah, good catch. Was a little surprised it wasn't available as a way, but I guess it makes sense. Not sure if there are defined "sledding trails" in parks...
