### ISSUE TITLE
Implement Imagery-based Places Editor Viewer map

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-editor#74]
Will incorporate current color-blind-compatible symbolization, highlight Places data by visually subduing the OSM data, and will overall make the transition from View to Edit more seamless.

**Comment by jakecoolidge** [comment]
Here's [the current draft.](http://www.nps.gov/maps/full.html?mapId=74317486-92fe-4d48-9641-dfc79c17778d)

**Comment by nateirwin** [comment]
I believe we can close this one, @jakecoolidge?

**Comment by makella** [comment]
@jakecoolidge it looks like you aren't using Frutiger for place labels in the map? Just curious if that was an oversight or because you like this other font for place labels better?

Thanks, mamata
