### ISSUE TITLE
symbolization of unclassified vs residential roads

### ISSUE THREAD

**Issue by ethomas33** [nationalparkservice/places-editor#76]
While editing in Places Editor I am struggling to make sure I have actually changed all unclassified roads to residential where appropriate because they have identical symbolization. Is it possible to change color or other appearance?

**Comment by jimmyrocks** [comment]
unclassified will be changed to a very light shade of gray

**Comment by jakecoolidge** [comment]
I've updated the preview mode so it will match when you update, @jimmyrocks .

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-editor/commit/96a83a5f13f8ad94617e36660e876ab8eb856dcd

**Comment by ethomas33** [comment]
@jimmyrocks should this be visible at this point on my end?

**Comment by jimmyrocks** [comment]
Change color to #bbbbbb

**Comment by jimmyrocks** [comment]
Yes, they aren't very different, but they are a little different. If it's
not different enough, we can make the unclassified roads darker. I just set
it back to the default for iD, we weren't sure if it was dark enough, but
thought it was a good starting point.

**Comment by ethomas33** [comment]
I think it is only visible when you are zoomed out but when you zoom in they all turn white. Are you seeing the same thing?
