### ISSUE TITLE
Background - None

### ISSUE THREAD

**Issue by ethomas33** [nationalparkservice/places-editor#78]
Should background none remove all satellite images from the background? If so it isn't changing anything.

**Comment by nateirwin** [comment]
I'm working on this as we speak. There are a few strange things happening with Editor. In short, it doesn't seem to be properly recognizing background and overlay parameters passed in via the URL. I believe this is related, and will hopefully have a fix out soon.

**Comment by jimmyrocks** [comment]
I ran an update last night (unclassified road colors and forcing lower case
unit codes) so this is probably related to that.

**Comment by nateirwin** [comment]
Yeah, `make` is failing for me. I'll push my latest if you want to take a look.
