### ISSUE TITLE
Server Error - unable to get to editor

### ISSUE THREAD

**Issue by ethomas33** [nationalparkservice/places-editor#80]
![404 error](https://cloud.githubusercontent.com/assets/12806793/9171595/f2208d4a-3f3a-11e5-84f3-5c2e8bee059b.PNG)

**Comment by nateirwin** [comment]
We consolidated the view and edit interfaces. Here's the new URL: http://insidemaps.nps.gov/places/editor/.

**Comment by nateirwin** [comment]
We're redirecting from both /places/edit/ and /places/view/ now, so this is fixed.

Sorry about the issue!
