### ISSUE TITLE
Updates to Places Editor view mode map

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-editor#81]
Provide visual cues in Places Editor that direct users to areas of parks that are populated by features/points of interest. Possible strategies to accomplish this:

- Display Visitor Centers with distinct symbols at lower zoom levels. Currently, all points of interest, regardless of type, display at zoom 9, but individual symbol types do not display until zoom 12. 
- Label park districts where we have this data in Places.
- Choose a color for the general point of interest symbol (currently translucent white) that better contrasts with the imagery base.

**Comment by cwlawlis802** [comment]
Moving this over from https://github.com/nationalparkservice/places-editor/issues/84:

This is the default zoom for First State National Historical Park (FRST) in Editor: http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=10.39/-75.5504/39.5020&overlays=park-tiles-overlay, which includes a number of land parcels spread out across a relatively large area. These other parcels (south of the primary, labeled boundary) are very difficult to locate in Editor, especially with the imagery backdrop.

We should consider adding multiple labels to make identifying these distributed parcels easier.

**Comment by cwlawlis802** [comment]
Let's make a note to take screenshots before and after the release of this update, specifically with the "data call update" blog post in mind.

**Comment by jakecoolidge** [comment]
Completed; moving [the FRST boundary and labeling issue](https://github.com/nationalparkservice/places-data/issues/160) to places-data. Brief list of improvements specified [here.](https://github.com/nationalparkservice/mapbox-studio-projects/tree/master/places_editor_viewer)
