### ISSUE TITLE
Labeling parks with spread out parcels/boundaries 

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#84]
This is the default zoom for First State National Historical Park (FRST) in Editor: http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=10.39/-75.5504/39.5020&overlays=park-tiles-overlay, which includes a number of land parcels spread out across a relatively large area. These other parcels (south of the primary, labeled boundary) are very difficult to locate in Editor, especially with the imagery backdrop.

We should consider adding multiple labels to make identifying these distributed parcels easier, along with increasing the contrast between park boundaries and the underlying imagery (which probably deserves a second issue).

cc @jakecoolidge @mtaylorlong

**Comment by jakecoolidge** [comment]
Yes, the contrast issue is open [here](https://github.com/nationalparkservice/places-editor/issues/83), and the general issue to improve the map is open [here](https://github.com/nationalparkservice/places-editor/issues/81).

**Comment by cwlawlis802** [comment]
Closing this down, can track multi-parcel labeling in general improvement issue https://github.com/nationalparkservice/places-editor/issues/81.
