### ISSUE TITLE
Integrate Symbol Library 2.0

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-editor#91]

**Comment by nateirwin** [comment]
@jakecoolidge: Sounds like this is done. Can you check it out and verify, and, if things are good, close this issue out?

**Comment by jakecoolidge** [comment]
@jimmyrocks just pushed this out; waiting for the changes to take effect.

**Comment by jakecoolidge** [comment]
verified new symbols are available in Places Editor.
