### ISSUE TITLE
Parking lot area icon not rendering properly

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#93]
Currently rendering as default icon and not pulling from npmap-symbol-library:

![parking_lot_area_preset](https://cloud.githubusercontent.com/assets/1238636/10529732/c874b7c6-735d-11e5-9227-f7ed90ccefe9.jpg)

Set to `npmap-symbol-library`, `parking-black` in the spreadsheet, so not entirely sure what's going on here.

**Comment by jimmyrocks** [comment]
This is a bug with places-data, moving issue there
