### ISSUE TITLE
Add Places Editor Preset: Boardwalk

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-editor#94]
My trip to Yellowstone reminded me of a common trail type that isn't currently represented in our Placed Editor Presets: **Boardwalk**. Yellowstone is covered in boardwalks, and all of the detailed park maps use a special line symbol to denote their presence. I imagine that many parks with marshes, wetlands, dunes, etc. have boardwalks and would be interested in distinguishing between these walkways and regular sidewalks or trails.

The OSM community hasn't really rallied around a method for mapping boardwalks. The OSM Wiki suggests adding them as a type of bridge (bridge=boardwalk), but I've also seen instances of classifying them as a footway with "boardwalk" as the surface (highway=footway, surface=boardwalk). I prefer this second option because we'll likely be classifying them under trails. I've also seen arguments to use surface=wood, but some boardwalks are wood and newer ones are wood-like plastic – I think what's important is that they are slightly elevated boards to create a nice flat walkway over a delicate or uneven landscape: a boardwalk.

My recommendation for Editor: 

Name | Superclass | Class | OSM Tags
--- | --- | --- | ---
Boardwalk | Trail | Non-Motorized | {"highway":"footway","surface:boardwalk"}

@jimmyrocks, @cwlawlis802, @jakecoolidge: What do y'all think?

**Comment by cwlawlis802** [comment]
This sounds good to me. It seems `{"bridge":"boardwalk"}` is the more common tag, with ~1,600 in OSM, while there are ~350 tagged `{"surface":"boardwalk"}`. The underlying tag doesn't really affect the preset's superclass, so I would be okay using `{"bridge":"boardwalk"}`, but I will defer to @jimmyrocks on that.

**Comment by mtaylorlong** [comment]
@cwlawlis802: I suppose you're right that it doesn't really matter on our end, so if bridge=boardwalk is the most accepted, we can use it. 

@jimmyrocks: Would it make sense to use bridge=boardwalk AND highway=footway?

Either way, I'd love to get it added as a preset and rendered into our places data source so I can use it in the YELL Places Mobile basemap.

**Comment by jimmyrocks** [comment]
Adding bridge: boardwalk will change the bridge t/f field in the vector
tiles to true
we could specifically ignore that case

**Comment by mtaylorlong** [comment]
Well, perhaps that means it would make more sense to use {"highway":"footway","surface:boardwalk"}. @jimmyrocks: Would you find this acceptable?

**Comment by jimmyrocks** [comment]
I'm voting for "surface":"boardwalk" since we don't want to render all
boardwalks as bridges

**Comment by mtaylorlong** [comment]
Great! Is there anything I can help with to get this into editor? If we need a special icon, I could whip something up...

**Comment by jimmyrocks** [comment]
You can add it to the spreadsheet:
https://docs.google.com/spreadsheets/d/1XFqkmIYMEp73q9flgNto9QJim6N5hbacgkUAgdf0rhE/edit#gid=0

And if you want to add an icon to npmap-symbol-library, that would be cool
as well.

I'll probably run another update to the tags in editor today, but the icons
won't get an update until the next release of iD, which is set to be Fri or
Mon.

**Comment by cwlawlis802** [comment]
Issue now here https://github.com/nationalparkservice/places-data/issues/344.
