### ISSUE TITLE
Double-tagging eliminates symbol

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#97]
When double-tagging a node, e.g. as amenity:parking, tourism:viewpoint, and viewpoint_type:overlook, no symbol at all (?) is present. Same as when amenity:parking and highway:trailhead. 

Example: Places ID 4155026

IMHO any other tag should take precedence over parking symbols....

**Comment by cwlawlis802** [comment]
Currently, our recommended best practice is to add each "service" (i.e. each different POI type) as a separate node.

The icon is set by a matchScore field in Editor, which is currently the same for each preset. So, when multiple POI types are set for one node, Editor does not know which icon to display and therefore does not show one at all.

This is an interesting issue, though, and one that we will look into further. If we were to embrace adding multiple "service" types to single nodes, we would have to develop a way to query each "service" individually from each node, which is currently not supported.

Thanks for flagging @tpcolson - closing for now.
