### ISSUE TITLE
Preset-classes doesn't translate to external download

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-editor#98]
When tagging as per https://docs.google.com/spreadsheets/d/1XFqkmIYMEp73q9flgNto9QJim6N5hbacgkUAgdf0rhE/edit#gid=0, "class" is not attributed when downloading, e.g., the shapefile. 

E.g places ID has the following tags: {"name": "Messer Barn", "building": "barn", "historic": "yes", "nps:fmss_id": "62771", "nps:building_id": "{C022ABD8-DBC4-48F9-8188-1E9414915CA0}"} yet class and superclass are both "Building", when superclass should in fact be "agricultural". 

Same as with w102594, tagged with "{"name": "Primative Baptist Church", "building": "church", "historic": "yes", "nps:fmss_id": "62660", "nps:building_id": "{39FFB0A4-24A0-498B-B896-2B5E2EE34D91}"}", class is "Building" when it should be "Place of Worship".

**Comment by cwlawlis802** [comment]
Are each of these points or areas?

All building areas ("Building Footprint") are housed under superclass Building, class Building.

**Comment by cwlawlis802** [comment]
Looks like these are areas - each will inherit superclass Building and class Building. 

Individual points of interest tagged as such will inherit the superclass/class combination you list above.

**Comment by jimmyrocks** [comment]
I just want to make a note on this that I will need to make sure the
CartoDB content is up to date with the latest tags.
