### ISSUE TITLE
Unable to edit outside unit boundary

### ISSUE THREAD

**Issue by cwlawlis802** [nationalparkservice/places-editor#99]
I'm able to add a point/line/area but cannot set a preset or add tags, nor can I delete the geometry after it has been added. 

Using Chrome, able to replicate in Safari.

Example URL: http://insidemaps.nps.gov/places/editor/#map=17.88/-73.93602/41.77645.

**Comment by jimmyrocks** [comment]
This was a bug introduced when switching to mapbox utfgrid. It was been fixed in the mapbox utfgrid. We have also moved back to cartodb, so this problem is solved. I have added the latest version to inside maps.
